site_name: "Statworx Project Template"
site_description: "Official statworx template for data science project using in kedro."
copyright: Made with ❤ from Statworx
use_directory_urls: false
repo_url: https://github.com/AnHo4ng/statworx-python-ds-template
repo_name: AnHo4ng/statworx-python-ds-template

theme:
  palette:
    scheme: statworx
  name: material
  favicon: assets/favicon.jpg
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.code.annotate
    - toc.integrate
    - navigation.top

extra_css:
  - assets/css/extras.css
  - assets/css/shortcut.css
  - assets/css/style.css
  - assets/css/mkdocstrings.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/statworx
    - icon: fontawesome/brands/medium
      link: https://medium.com/@statworx_blog
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/statworx
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/statworx
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/statworx
    - icon: fontawesome/brands/xing
      link: https://www.xing.com/companies/statworx
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/statworx

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

extra_javascript:
  - assets/javascripts/shortcuts.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search

nav:
  - Overview: index.md
  - User Guide:
      - Style Guide: style_guide.md
      - Dev Tools: dev_tools.md
      - Code Tools: code_tools.md
      - Test Guide: testing.md
      - IDE Integration: ide_integration.md
  - Contribution Guide: contribution.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Licence: licence.md
